package TravelBussiness.WebDriverTest;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import pageObjects.LoginPage;



public class CarrierTest extends WebDriverTestBase {
	WebDriver driver;
	LoginPage onLoginPage;
	String user = "admin@mailinator.com";
	String pass = "admin";
	String carrierName = "AutoGenerated";
	
	@Test (priority = 0)
	public void CreateCarrierTest() {
		
		onLoginPage = PageFactory.initElements(driver, LoginPage.class);
		onLoginPage.open();
	}
		
	@BeforeMethod
	public void setUp () {
		driver = new FirefoxDriver ();
		driver.manage().window().maximize();
	}
	
	@AfterMethod
	    public void tearDown() {
		//logout
		driver.findElement(By.xpath("/html/body/div/nav/div[2]/div/a/span")).click();
		driver.findElement(By.xpath("/html/body/div/nav/div[2]/div/ul/li/a")).click();
		//driver.quit();
	    
	    }

}
